extends SceneTree
const SHADOW=preload("res://scripts/world/source_shadow.gd")
var failures:Array[String]=[]
var checks:=0
func _initialize()->void:call_deferred("_run")
func check(value:bool,message:String)->void:
	checks+=1
	if not value:failures.append(message)
func _run()->void:
	var map=Node3D.new()
	root.add_child(map)
	var camera=Camera3D.new()
	root.add_child(camera)
	camera.position=Vector3(1.234,1.7,-4.567)
	camera.current=true
	var static_mesh=MeshInstance3D.new()
	static_mesh.mesh=BoxMesh.new()
	map.add_child(static_mesh)
	var moving=MeshInstance3D.new()
	moving.mesh=BoxMesh.new()
	root.add_child(moving)
	var disabled=MeshInstance3D.new()
	disabled.mesh=BoxMesh.new()
	disabled.cast_shadow=GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	root.add_child(disabled)
	var shadow=SHADOW.new()
	map.add_child(shadow)
	shadow.set_process(false)
	shadow._process(0.0)
	check(shadow.viewport.size==Vector2i(2048,2048) and shadow.camera.projection==Camera3D.PROJECTION_ORTHOGONAL and shadow.camera.size==80,"Source shadow uses a 2048px,80m orthographic square")
	check(shadow.camera.near==0.5 and shadow.camera.far==200,"Source depth range is half-meter through200m")
	var source_focus=Vector3(1.25,1.71875,-4.5703125)
	var expected=source_focus+Vector3(0.5,1,0.35).normalized()*88
	check(shadow.camera.position.is_equal_approx(expected),"Source shadow camera follows world-space texel-snapped player position")
	check(shadow.proxies.size()==2,"Only source casting geometry enters depth scene")
	check(not shadow.proxies[static_mesh.get_instance_id()].dynamic and shadow.proxies[moving.get_instance_id()].dynamic,"Static map geometry is cached independently of animated actors")
	moving.position=Vector3(2,3,4)
	shadow._process(0.0)
	check(shadow.proxies[moving.get_instance_id()].node.position==moving.position,"Animated caster world transforms update without a scene rebuild")
	moving.hide()
	shadow._process(0.0)
	check(not shadow.proxies[moving.get_instance_id()].node.visible,"Hidden replay/live actors stop casting")
	var added=MeshInstance3D.new()
	added.mesh=BoxMesh.new()
	root.add_child(added)
	check(shadow._dirty,"Geometry arrival invalidates the cached caster list")
	shadow._process(0.0)
	check(shadow.proxies.has(added.get_instance_id()),"Newly created equipment/streak geometry can enter the shadow pass")
	var id=added.get_instance_id()
	added.free()
	check(not shadow.proxies.has(id),"Removed geometry releases its depth proxy immediately")
	shadow.free()
	static_mesh.free()
	moving.free()
	disabled.free()
	camera.free()
	map.free()
	await process_frame
	if failures.is_empty():print("SOURCE SHADOW PASS: %d checks"%checks)
	else:
		for failure in failures:push_error(failure)
	quit(0 if failures.is_empty() else 1)
